AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://artifacts-bucket-915028409560/edb546fc4d2bf17e8209d0d6315d476d
      Description: ''
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          TARGET_BUCKET: intermediate-store-915028409560
