AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: s3://artifacts-bucket-915028409560/68c02e67e92e03b0c4761e869b1bcbcc
      Description: ''
      MemorySize: 512
      Timeout: 900
      Environment:
        Variables:
          TARGET_BUCKET: intermediate-store-915028409560
